### ISSUE TITLE
HTML & CSS 

### ISSUE THREAD

**Issue by alaa-sahloub** [GSG-G9/Autocomplete_-Alaa_Sahloub#3]
handle Html & Css for webpage search input and dev for search autocomplete words

**Comment by gurnoor-garry** [comment]
Hey

I was interested to resolve this issue. Could you elaborate the issue??

**Comment by alaa-sahloub** [comment]
> Hey
> 
> I was interested to resolve this issue. Could you elaborate the issue??

It's an issue to write HTML and CSS code for the web page. It's supposed to be closed because I finished it.
